# The runtime travels inside the skill (keel-cloud `canon/designs/keel-skill-design.md` §3.1,
# invariant D2). There is one copy of keel-runtime's source in the world and it is in
# keel-runtime; every other copy is made by this build step from one named commit, which is why
# `keel_runtime/` is gitignored here and `RUNTIME_VERSION` -- the record of *which* runtime this
# skill carries -- is not.
#
#   make runtime    copy ../keel-runtime/keel_runtime/ in, and stamp RUNTIME_VERSION
#   make dist       build the four packaging trees (plus the marketplace) from this one source
#   make release    cut/force-update the `release` branch from dist/plugin/, and push it
#   make test       this repository's own tests, offline, against fake and real runtimes
#   make clean      remove the copied package, the built trees and the caches
#
# **`make dist` copies; it never transforms** (design §8.1). The only generated bytes in any tree
# are the two manifests and the version they carry, and `dist/speckit-catalog-entry.json`, which
# is read back out of the manifest it was generated beside so the submission and the manifest
# cannot disagree. Four hand-maintained copies is the failure this design exists to prevent; a
# copy a build step makes and a test compares (L1, `tests/test_dist.py`) is not that failure.

SHELL := /bin/bash

# The sibling checkout the package is copied from. Overridable so CI can point at a fresh clone
# of `keeldiscovery/keel-runtime` rather than a working tree beside this one.
KEEL_RUNTIME_SRC ?= ../keel-runtime

# The interpreter the tests run under. The floor is 3.9 (design §4.1) and the matrix holds
# 3.9-3.13; `make test` runs whichever one is asked for and defaults to the ambient python3.
PYTHON ?= python3

# One version, everywhere (D7). `VERSION` is this skill's; `RUNTIME_VERSION` is which keel-runtime
# it carries, stamped by `make runtime`. A RUNTIME_VERSION bump is a minor version of the skill:
# it changes which runtime a founder receives without changing any shape a caller reads.
VERSION := $(shell cat VERSION)

# The three things that are copied into every tree, identically, and nothing else (D1, D2).
SKILL_FILES := SKILL.md scripts keel_runtime

.PHONY: runtime dist release test clean

runtime:
	@set -euo pipefail; \
	src="$(KEEL_RUNTIME_SRC)"; \
	if [ ! -d "$$src/keel_runtime" ]; then \
	  echo "make runtime: $$src has no keel_runtime/ package -- set KEEL_RUNTIME_SRC" >&2; \
	  exit 1; \
	fi; \
	if ! git -C "$$src" rev-parse --git-dir >/dev/null 2>&1; then \
	  echo "make runtime: $$src is not a git checkout; a copy whose provenance cannot be" >&2; \
	  echo "  named is the two-runtimes failure D2 exists to prevent" >&2; \
	  exit 1; \
	fi; \
	if ! commit=$$(git -C "$$src" rev-parse --verify --quiet HEAD); then \
	  echo "make runtime: $$src is not on a commit (no HEAD) -- nothing to name" >&2; \
	  exit 1; \
	fi; \
	if [ -n "$$(git -C "$$src" status --porcelain)" ]; then \
	  echo "make runtime: $$src is dirty. RUNTIME_VERSION would name a commit whose" >&2; \
	  echo "  working tree is not what was copied. Commit or stash there first:" >&2; \
	  git -C "$$src" status --short >&2; \
	  exit 1; \
	fi; \
	version=$$(awk -F'"' '/^__version__/ {print $$2; exit}' "$$src/keel_runtime/__init__.py"); \
	if [ -z "$$version" ]; then \
	  echo "make runtime: no __version__ in $$src/keel_runtime/__init__.py" >&2; \
	  exit 1; \
	fi; \
	tag=$$(git -C "$$src" describe --tags --exact-match 2>/dev/null || true); \
	if [ -n "$$tag" ]; then stamp="$$tag"; else stamp="$$version+$$(git -C "$$src" rev-parse --short HEAD)"; fi; \
	rm -rf keel_runtime; \
	cp -R "$$src/keel_runtime" keel_runtime; \
	find keel_runtime -name '__pycache__' -type d -prune -exec rm -rf {} +; \
	find keel_runtime -name '*.py[co]' -delete; \
	printf '%s\n' "$$stamp" > RUNTIME_VERSION; \
	echo "keel_runtime/ <- $$src at $$commit"; \
	echo "RUNTIME_VERSION: $$stamp"

# `place_skill <destination>` -- the one skill, copied. Every tree gets these bytes and no others;
# L1 asserts all four are byte-identical to this source and to each other.
define place_skill
	mkdir -p "$(1)"; \
	for item in $(SKILL_FILES); do cp -R "$$item" "$(1)/"; done; \
	find "$(1)" -name '__pycache__' -type d -prune -exec rm -rf {} + ; \
	find "$(1)" -name '*.py[co]' -delete
endef

# `stamp <template> <destination>` -- the only transformation in this file: $${VERSION}.
define stamp
	mkdir -p "$$(dirname "$(2)")"; \
	sed 's|[$$][{]VERSION[}]|$(VERSION)|g' "$(1)" > "$(2)"
endef

dist:
	@set -euo pipefail; \
	if [ ! -f keel_runtime/__main__.py ]; then \
	  echo "make dist: no keel_runtime/ here -- run \`make runtime\` first (D2)" >&2; \
	  exit 1; \
	fi; \
	if [ ! -s VERSION ] || [ ! -s RUNTIME_VERSION ]; then \
	  echo "make dist: VERSION and RUNTIME_VERSION must both name something (D7)" >&2; \
	  exit 1; \
	fi; \
	rm -rf dist; \
	\
	echo "dist/plugin        Claude Code plugin"; \
	$(call stamp,packaging/plugin/plugin.json.in,dist/plugin/.claude-plugin/plugin.json); \
	$(call place_skill,dist/plugin/skills/keel-connect); \
	cp packaging/plugin/README.md dist/plugin/README.md; \
	cp LICENSE dist/plugin/LICENSE; \
	\
	echo "dist/speckit       Spec Kit extension"; \
	$(call stamp,packaging/speckit/extension.yml.in,dist/speckit/extension.yml); \
	$(call place_skill,dist/speckit); \
	cp -R packaging/speckit/commands dist/speckit/commands; \
	mkdir -p dist/speckit/tests; \
	cp packaging/speckit/tests/test-install.sh dist/speckit/tests/test-install.sh; \
	chmod +x dist/speckit/tests/test-install.sh; \
	cp packaging/speckit/README.md dist/speckit/README.md; \
	cp packaging/speckit/CHANGELOG.md dist/speckit/CHANGELOG.md; \
	cp LICENSE dist/speckit/LICENSE; \
	$(PYTHON) packaging/catalog_entry.py dist/speckit/extension.yml \
	  dist/speckit-catalog-entry.json; \
	\
	echo "dist/bare          the tree with no manifest at all"; \
	$(call place_skill,dist/bare/keel-connect); \
	cp packaging/bare/install.sh dist/bare/install.sh; \
	chmod +x dist/bare/install.sh; \
	cp packaging/bare/install.ps1 dist/bare/install.ps1; \
	cp LICENSE dist/bare/LICENSE; \
	\
	echo "dist/copilot-repo  the directory a team commits"; \
	$(call place_skill,dist/copilot-repo/.github/skills/keel-connect); \
	cp packaging/copilot/repo/README.md dist/copilot-repo/README.md; \
	cp LICENSE dist/copilot-repo/LICENSE; \
	\
	echo "dist/marketplace   the keeldiscovery/keel-marketplace tree (the repo is the founder's to create)"; \
	$(call stamp,packaging/marketplace/marketplace.json.in,dist/marketplace/.claude-plugin/marketplace.json); \
	mkdir -p dist/marketplace/.github/plugin; \
	cp dist/marketplace/.claude-plugin/marketplace.json dist/marketplace/.github/plugin/marketplace.json; \
	cp packaging/marketplace/README.md dist/marketplace/README.md; \
	cp LICENSE dist/marketplace/LICENSE; \
	\
	echo "VERSION $(VERSION)  RUNTIME_VERSION $$(cat RUNTIME_VERSION)"

# The `release` branch (design §8.2, decision 14): an orphan branch whose root is `dist/plugin/`
# built from this exact `master` commit, and nothing else -- the tree `keeldiscovery/keel-marketplace`
# points `claude plugin install keel@keel` and `copilot plugin install keel@keel` at. Reproducible:
# built with `git commit-tree` rather than a checkout, so no working tree or index is disturbed,
# and the commit's author/committer dates are pinned to `master`'s own commit date (not to when
# `make release` happened to run), so the same `master` commit and the same `../keel-runtime`
# checkout build the identical tree and the identical commit object every time.
release:
	@set -euo pipefail; \
	if [ -n "$$(git status --porcelain)" ]; then \
	  echo "make release: working tree is dirty -- the release branch is cut from a committed" >&2; \
	  echo "  master, never from bytes nobody can name. Commit or stash first:" >&2; \
	  git status --short >&2; \
	  exit 1; \
	fi; \
	$(MAKE) dist; \
	if [ ! -f dist/plugin/.claude-plugin/plugin.json ]; then \
	  echo "make release: dist/plugin/.claude-plugin/plugin.json is missing after \`make dist\`" >&2; \
	  exit 1; \
	fi; \
	commit=$$(git rev-parse HEAD); \
	short=$$(git rev-parse --short HEAD); \
	runtime_version=$$(cat RUNTIME_VERSION); \
	source_date=$$(git show -s --format=%aI HEAD); \
	index=$$(mktemp); rm -f "$$index"; \
	tree=$$(GIT_INDEX_FILE="$$index" GIT_WORK_TREE="$(CURDIR)/dist/plugin" git add -A -- . >&2 \
	  && GIT_INDEX_FILE="$$index" git write-tree); \
	rm -f "$$index"; \
	message=$$(printf 'release %s: dist/plugin/ built from master %s (RUNTIME_VERSION %s)\n\nAn orphan root commit -- the plugin tree `make dist` builds from this exact master\ncommit, and nothing else. `make release` force-updates this branch to a fresh root\nlike this one whenever master or RUNTIME_VERSION moves.\n' \
	  "$(VERSION)" "$$short" "$$runtime_version"); \
	new_commit=$$(GIT_AUTHOR_DATE="$$source_date" GIT_COMMITTER_DATE="$$source_date" \
	  git commit-tree "$$tree" -m "$$message"); \
	git branch -f release "$$new_commit"; \
	git push --force origin release:refs/heads/release; \
	echo "release -> $$new_commit  (orphan root; dist/plugin/ from master $$short, RUNTIME_VERSION $$runtime_version)"

test:
	$(PYTHON) -m unittest discover tests -v

clean:
	rm -rf keel_runtime dist
	find . -name '__pycache__' -type d -prune -exec rm -rf {} +
	find . -name '*.py[co]' -delete
